//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallManufacturing.Database
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.BillOfMaterials = new HashSet<BillOfMaterials>();
            this.PurchaseMaterial = new HashSet<PurchaseMaterial>();
        }
    
        public long id { get; set; }
        public string title { get; set; }
        public long unit { get; set; }
        public int min_residue { get; set; }

        public decimal quantityInStock
        {
            get
            {
                using (var context = new manufacturingEntities())
                {
                    decimal result = 0;

                    var purchases = context.PurchaseMaterial.Where(p => p.material == this.id).ToList();

                    foreach (var purchase in purchases)
                    {
                        result += decimal.Parse(purchase.quantity.ToString());
                    }

                    var productMaterials = context.BillOfMaterials.Where(pm => pm.material == this.id).ToList();

                    foreach (var productMaterial in productMaterials)
                    {
                        var orderProducts = context.OrderProduct.Where(op => op.product == productMaterial.product).ToList();

                        foreach (var orderProduct in orderProducts)
                        {
                            result -= decimal.Parse(orderProduct.quantity.ToString());
                        }
                    }

                    return result;
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfMaterials> BillOfMaterials { get; set; }
        public virtual Unit Unit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseMaterial> PurchaseMaterial { get; set; }
    }
}
