//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallManufacturing.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAssignment
    {
        public long production_order { get; set; }
        public long employee { get; set; }
        public Nullable<long> equipment { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Equipment Equipment1 { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
