//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallManufacturing.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public long production_order { get; set; }
        public long product { get; set; }
        public int quantity { get; set; }
    
        public virtual Product Product1 { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
