//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallManufacturing.Database
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BillOfMaterials = new HashSet<BillOfMaterials>();
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public long id { get; set; }
        public string article { get; set; }
        public string title { get; set; }
        public string description { get; set; }

        public string materials
        {
            get
            {
                using (var context = new manufacturingEntities())
                {
                    var productMaterials = context.BillOfMaterials.Where(pm => pm.product == this.id).ToList();

                    var materialStrings = productMaterials.Select(pm => { string materialName = pm.Material1.title; return $"{materialName} - {pm.quantity}"; }).ToList();

                    string result = string.Join(", ", materialStrings);

                    return result;
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOfMaterials> BillOfMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
